name: banking
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg_provider: ^1.0.3
  hexcolor: ^2.0.6

  graphql_flutter: ^5.0.1
  equatable: ^2.0.3



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Regular.ttf
    - family: Fredoka Bold
      fonts:
        - asset: assets/fonts/Fredoka-Bold.ttf
    - family: Fredoka SemiBold
      fonts:
        - asset: assets/fonts/Fredoka-SemiBold.ttf
    - family: Fredoka Light
      fonts:
        - asset: assets/fonts/Fredoka-Light.ttf


